			<div class="homepackage">
				<li class="homepackagediv">
					<div>
						<img src="image/Kashmir.jpg" class="packageimg"><br>
					</div>
					<div class="packagename">
						Kashmir Tour Packages
					</div>
					<div class="packagetext">
						We offers a large verity of Kashmir tours
					</div>
					<div class="packagelink">
						<a href="Tour.php?id=2">Click here for a list of tours </a>
					</div>
				</li>
				
				<li class="homepackagediv">
					<div>
						<img src="image/LehLadakh.jpg" class="packageimg"><br>
					</div>
					<div class="packagename leh-ladakh">
						Leh-Ladakh Tour Packages
					</div>
					<div class="packagetext leh-ladakhtext">
						We offers a large verity of Leh-Ladakh tours
					</div>
					<div class="packagelink leh-ladakh">
						<a href="Tour.php?id=3">Click here for a list of tours </a>
					</div>
				</li>
				
				<li class="homepackagediv">
					<div>
						<img src="image/Kerala.jpg" class="packageimg"><br>
					</div>
					<div class="packagename kerala">
						Kerala Tour Packages
					</div>
					<div class="packagetext keralatext">
						We offers a large verity of Kerala tours
					</div>
					<div class="packagelink kerala">
						<a href="Tour.php?id=1">Click here for a list of tours </a>
					</div>
				</li>
				
				<li class="homepackagediv">					
					<div>
						<img src="image/Goa.jpg" class="packageimg"><br>
					</div>
					<div class="packagename Goa">
						Goa Tour Packages
					</div>
					<div class="packagetext Goatext">
						We offers a large verity of Goa tours
					</div>
					<div class="packagelink Goa">
						<a href="Tour.php?id=4">Click here for a list of tours </a>
					</div>
				</li>
			</div>	

			<div class="morepackage">
				<a href="Destination.php">Click here to see a more packages </a>
			</div>